# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-featured_pages-extension}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex K"]
  s.date = %q{2010-09-06}
  s.description = %q{Create collection of featured pages}
  s.email = %q{flskif@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/featured_pages_sets_controller.rb",
     "app/helpers/admin/featured_pages_sets_helper.rb",
     "app/models/featured_pages_set.rb",
     "app/views/admin/featured_pages_sets/_form.html.haml",
     "app/views/admin/featured_pages_sets/edit.html.haml",
     "app/views/admin/featured_pages_sets/index.html.haml",
     "app/views/admin/featured_pages_sets/new.html.haml",
     "app/views/admin/featured_pages_sets/remove.html.haml",
     "app/views/admin/pages/_featured_sets.html.haml",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "db/migrate/20100901185915_create_featured_pages_sets.rb",
     "db/migrate/20100901200704_create_set_page_relationships.rb",
     "featured_pages_extension.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/featured_pages/interface.rb",
     "lib/featured_pages/page_extension.rb",
     "lib/featured_pages/pages_controller_extension.rb",
     "lib/tasks/featured_pages_extension_tasks.rake",
     "public/stylesheets/admin/featured_pages.css",
     "spec/controllers/admin/featured_pages_sets_controller_spec.rb",
     "spec/helpers/admin/featured_pages_sets_helper_spec.rb",
     "spec/models/featured_pages_set_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flskif/radiant-featured_pages-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Featured Pages Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/featured_pages_sets_controller_spec.rb",
     "spec/helpers/admin/featured_pages_sets_helper_spec.rb",
     "spec/models/featured_pages_set_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

